/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.buk.view;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author joan.toro
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        mnuBarMain = new javax.swing.JMenuBar();
        mniMantenedor = new javax.swing.JMenu();
        mniEmpresa = new javax.swing.JMenuItem();
        mniUbicacion = new javax.swing.JMenuItem();
        mniDepartamento = new javax.swing.JMenuItem();
        mniEmpleado = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buk : App");

        pnlMain.setPreferredSize(new java.awt.Dimension(760, 460));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        mniMantenedor.setText("Mantenedor");

        mniEmpresa.setText("Empresa");
        mniEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpresaActionPerformed(evt);
            }
        });
        mniMantenedor.add(mniEmpresa);

        mniUbicacion.setText("Ubicacion");
        mniUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUbicacionActionPerformed(evt);
            }
        });
        mniMantenedor.add(mniUbicacion);

        mniDepartamento.setText("Departamento");
        mniDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDepartamentoActionPerformed(evt);
            }
        });
        mniMantenedor.add(mniDepartamento);

        mniEmpleado.setText("Empleado");
        mniEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleadoActionPerformed(evt);
            }
        });
        mniMantenedor.add(mniEmpleado);

        mnuBarMain.add(mniMantenedor);

        mniSalir.setText("Salir");
        mnuBarMain.add(mniSalir);

        setJMenuBar(mnuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpresaActionPerformed
        showPanel("Empresa", new frmEmpresa());
    }//GEN-LAST:event_mniEmpresaActionPerformed

    private void showPanel(String titulo, JPanel form) {
        // TODO add your handling code here:
        this.setTitle("Buk : " + titulo.toUpperCase());
        form.setSize(800, 530);
        form.setLocation(0,0);
        
        pnlMain.removeAll();
        pnlMain.add(form, BorderLayout.CENTER);
        pnlMain.revalidate();
        pnlMain.repaint();
    }

    private void mniUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUbicacionActionPerformed
        // TODO add your handling code here:
       showPanel("Ubicación", new frmUbicacion());
    }//GEN-LAST:event_mniUbicacionActionPerformed

    private void mniDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDepartamentoActionPerformed
        // TODO add your handling code here:
        showPanel("Departamento", new frmDepartamento());
    }//GEN-LAST:event_mniDepartamentoActionPerformed

    private void mniEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleadoActionPerformed
        // TODO add your handling code here:
        showPanel("Empleado", new frmEmpleado());
    }//GEN-LAST:event_mniEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mniDepartamento;
    private javax.swing.JMenuItem mniEmpleado;
    private javax.swing.JMenuItem mniEmpresa;
    private javax.swing.JMenu mniMantenedor;
    private javax.swing.JMenu mniSalir;
    private javax.swing.JMenuItem mniUbicacion;
    private javax.swing.JMenuBar mnuBarMain;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
